import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  styleOne,
  styleTwo,
  styleThree,
  styleFour,
  styleFive,
  styleSix,
  styleSeven,
  styleEight,
  styleNine,
  styleTen,
  styleEleven,
  styleTwelve,
  styleThirteen,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "/contact",
  },
  {
    _id: 1005,
    title: "AI Tool",
    link: "/aitool",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: newArrOne,
    productName: "Smart Watch",
    price: "250.00",
    des: "Latest model with advanced health tracking",
    badge: true,
    category: "Electronics",
  },
  {
    _id: "202",
    img: newArrTwo,
    productName: "Nike Shoes",
    price: "120.00",
    des: "Premium comfort sports shoes",
    badge: true,
    category: "Fashion",
  },
  {
    _id: "203",
    img: newArrThree,
    productName: "Leather Wallet",
    price: "80.00",
    des: "Handcrafted genuine leather wallet",
    badge: true,
    category: "Fashion",
  },
  {
    _id: "204",
    img: newArrFour,
    productName: "Wireless Earbuds",
    price: "150.00",
    des: "High-quality sound with noise cancellation",
    badge: true,
    category: "Electronics",
  },
];
// =================== Special Offer data End here ==============

// =================== Style Collection Start here =========
export const styleItems = [
  {
    _id: "s1",
    img: styleOne,
    productName: "Elegant Evening Dress",
    price: "225.00",
    color: "Black",
    badge: true,
    des: "Sophisticated evening dress perfect for formal occasions and special events.",
    category: "Dresses",
  },
  {
    _id: "s2",
    img: styleTwo,
    productName: "Classic Denim Jacket",
    price: "120.00",
    color: "Blue",
    badge: false,
    des: "Timeless denim jacket with a modern fit, versatile for casual everyday wear.",
    category: "Outerwear",
  },
  {
    _id: "s3",
    img: styleThree,
    productName: "Summer Linen Shirt",
    price: "85.00",
    color: "White",
    badge: true,
    des: "Lightweight linen shirt ideal for hot summer days, breathable and stylish.",
    category: "Tops",
  },
  {
    _id: "s4",
    img: styleFour,
    productName: "Casual Striped Tee",
    price: "45.00",
    color: "Navy/White",
    badge: false,
    des: "Comfortable striped t-shirt with a relaxed fit for everyday casual style.",
    category: "Tops",
  },
  {
    _id: "s5",
    img: styleFive,
    productName: "Vintage Style Blouse",
    price: "95.00",
    color: "Cream",
    badge: true,
    des: "Elegant blouse with vintage-inspired details, perfect for both work and leisure.",
    category: "Tops",
  },
  {
    _id: "s6",
    img: styleSix,
    productName: "Designer Leather Jacket",
    price: "320.00",
    color: "Brown",
    badge: true,
    des: "Premium leather jacket with designer details and exceptional craftsmanship.",
    category: "Outerwear",
  },
  {
    _id: "s7",
    img: styleSeven,
    productName: "Bohemian Maxi Dress",
    price: "155.00",
    color: "Multicolor",
    badge: false,
    des: "Flowing maxi dress with bohemian-inspired prints, perfect for summer events.",
    category: "Dresses",
  },
  {
    _id: "s8",
    img: styleEight,
    productName: "Business Casual Blazer",
    price: "190.00",
    color: "Gray",
    badge: true,
    des: "Tailored blazer that transitions seamlessly from office to evening occasions.",
    category: "Outerwear",
  },
  {
    _id: "s9",
    img: styleNine,
    productName: "Modern Chiffon Dress",
    price: "175.00",
    color: "Navy",
    badge: false,
    des: "Elegant chiffon dress with modern silhouette, perfect for semi-formal events.",
    category: "Dresses",
  },
  {
    _id: "s10",
    img: styleTen,
    productName: "Casual Button-Up Shirt",
    price: "75.00",
    color: "Light Blue",
    badge: true,
    des: "Versatile button-up shirt that pairs well with jeans or chinos for a smart casual look.",
    category: "Tops",
  },
  {
    _id: "s11",
    img: styleEleven,
    productName: "Patterned Summer Dress",
    price: "125.00",
    color: "Floral Print",
    badge: true,
    des: "Lightweight summer dress with a flattering silhouette and vibrant pattern.",
    category: "Dresses",
  },
  {
    _id: "s12",
    img: styleTwelve,
    productName: "Premium Wool Sweater",
    price: "145.00",
    color: "Burgundy",
    badge: false,
    des: "Soft wool sweater for cooler weather, combining comfort with sophisticated style.",
    category: "Tops",
  },
  {
    _id: "s13",
    img: styleThirteen,
    productName: "Designer Evening Gown",
    price: "395.00",
    color: "Emerald",
    badge: true,
    des: "Stunning designer evening gown for special occasions and formal events.",
    category: "Dresses",
  },
];
// =================== Style Collection End here ===========

// =================== PaginationItems Start here ===============
export const paginationItems = [
  {
    _id: "1",
    img: spfOne,
    productName: "Behind Graphic balck T-Shirt",
    price: "35.00",
    color: "Black and White",
    badge: true,
    des: "Premium quality cotton baseball cap with adjustable strap, perfect for casual wear.",
    category: "Fashion",
  },
  {
    _id: "2",
    img: spfTwo,
    productName: "White Cherry Sweatshirt",
    price: "180.00",
    color: "Walnut",
    badge: true,
    des: "Sleek and contemporary coffee table with storage shelf, ideal for modern living rooms.",
    category: "Furniture",
  },
  {
    _id: "3",
    img: spfThree,
    productName: "Spider Undercover",
    price: "125.00",
    color: "Black/Red",
    badge: true,
    des: "High-performance gaming headset with surround sound and noise cancellation.",
    category: "Electronics",
  },
  {
    _id: "4",
    img: spfFour,
    productName: "Adventure Hoodie",
    price: "220.00",
    color: "Gold/Green",
    badge: true,
    des: "Classic aviator sunglasses with polarized lenses and UV protection.",
    category: "Fashion",
  },
  {
    _id: "5",
    img: bestSellerOne,
    productName: "Vintage T-Shirt",
    price: "450.00",
    color: "Brown",
    badge: false,
    des: "Premium leather lounge chair with ottoman, combining comfort with modern design.",
    category: "Furniture",
  },
  {
    _id: "6",
    img: bestSellerTwo,
    productName: "Navy Knit Polo Shirt",
    price: "280.00",
    color: "Black, Silver",
    badge: true,
    des: "Advanced fitness tracker with heart rate monitoring, GPS, and sleep tracking.",
    category: "Electronics",
  },
  {
    _id: "7",
    img: bestSellerThree,
    productName: "Beige Linen Shirt",
    price: "170.00",
    color: "White, Beige",
    badge: false,
    des: "Premium linen clothing collection, perfect for summer comfort and style.",
    category: "Fashion",
  },
  {
    _id: "8",
    img: bestSellerFour,
    productName: "California Sweatshirt",
    price: "145.00",
    color: "White, Black",
    badge: true,
    des: "Voice-controlled LED floor lamp with adjustable colors and brightness levels.",
    category: "Home",
  },
  {
    _id: "9",
    img: newArrOne,
    productName: "Maroon Corduroy Shirt",
    price: "85.00",
    color: "Black",
    badge: true,
    des: "Scandinavian design wall clock with silent movement and modern aesthetics.",
    category: "Home",
  },
  {
    _id: "10",
    img: newArrTwo,
    productName: "Navy Blue  Polo T-Shirt",
    price: "550.00",
    color: "Silver/Blue",
    badge: true,
    des: "Premium chronograph watch with sapphire crystal and automatic movement.",
    category: "Fashion",
  },
  {
    _id: "11",
    img: newArrThree,
    productName: "Black Oversized Hoodie ",
    price: "120.00",
    color: "Natural",
    badge: true,
    des: "Eco-friendly bamboo storage containers and organizers for sustainable living.",
    category: "Home",
  },
  {
    _id: "12",
    img: newArrFour,
    productName: "White and Red Heart Sweatshirt",
    price: "95.00",
    color: "Multi-color",
    badge: false,
    des: "Interactive STEM learning kit with robotics and coding projects for children.",
    category: "Kids",
  },
  
];
// =================== PaginationItems End here =================

// =================== Sponsor Array ====================
export const sponsorData = [
  {
    _id: 1,
    heading: "Our Sponsor",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum voluptatum eum nisi laudantium adipisci earum!",
  },
];

// =================== Payment Card Array ====================
export const paymentCardData = [
  {
    _id: 1,
    img: spfOne,
    title: "Buy with credit card",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum voluptatum eum nisi laudantium adipisci earum!",
  },
  {
    _id: 2,
    img: spfTwo,
    title: "Buy with credit card",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum voluptatum eum nisi laudantium adipisci earum!",
  },
  {
    _id: 3,
    img: spfThree,
    title: "Buy with credit card",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum voluptatum eum nisi laudantium adipisci earum!",
  },
];
